### ISSUE TITLE
Request_Base with traefik

### ISSUE THREAD

**Issue by toxic0berliner** [convos-chat/convos#587]
Hello,

I've been unable to get convos working with traefik using the request_base headers. 
I did in the end manage to get it somewhat working using the CONVOS_REQUEST_BASE environment variable, but it's syntax is either only allowing a single host, or I couldn't find how to allow multiple request bases...
For example, my convos instance can be accessed at convos.example.com and at irc.example.com or webchat.example.com

My understanding was that using CONVOS_REVERSE_PROXY=1 environment variable, I should have been able to have traefik send the proper HTTP headers X-Request-Base to make it work using any of the above urls...

I do have traefik sucessfully forwarding to convos, I run convos in a docker container, and traefik builds it's config using the labels on the docker container, this is what I tried and that should have worked at least for one domain but did not even do that: 
```
version: "3"
services:
  convos:
    container_name: convos
    environment:
      - CONVOS_REVERSE_PROXY=1
      - CONVOS_SECURE_COOKIES=true
      - TZ=Europe/Paris
    hostname: convos
    image: nordaaker/convos:stable
    labels:
      traefik.http.middlewares.convos.headers.customrequestheaders.Host: 'https://convos.example.com/'
      traefik.http.middlewares.convos.headers.customrequestheaders.X-Request-Base: 'https://convos.example.com/'
      traefik.http.middlewares.convos.headers.customrequestheaders.X-Forwarded-Proto: 'https'
```
But somehow with that convos still did not let me login and complained about something insecure...

Any help in setting up convos with traefik as reverse proxy and possibly for any host matched in the rule of the ost would be very appreciated.
Or again, a way to setup more than one request_base using the env var...

Thanks in advance.

**Comment by jhthorsen** [comment]
I haven't used traefik myself I'm afraid, but I would very much like if this issue was resolved in a proper way, so we/I can update https://convos.chat/doc/reverse-proxy with a proper example config.

By translating the nginx config, I would guess something like this should work:

```
version: "3"
services:
  convos:
    image: nordaaker/convos:stable
    container_name: convos
    environment:
      - CONVOS_REVERSE_PROXY=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-secure.entrypoints=https"
      - "traefik.http.middlewares.convos.headers.customrequestheaders.Host=convos.example.com"
      - "traefik.http.middlewares.convos.headers.customrequestheaders.X-Request-Base=https://convos.example.com/"
```

What I don't understand is how traefik knows which SSL cert to use. Pretty sure a secure connection (meaning no self signed certs) is required for a proper Websocket connection.

Note to self: Update https://github.com/convos-chat/www.convos.chat/blob/master/doc/reverse-proxy.md with TLS/SSL examples.

**Comment by jhthorsen** [comment]
Other references:

- #447 - "Blank page with Docker+Traefik+Https"
- #518 - "CONVOS_LOCAL_SECRET not docummented"
- #583 - Maybe @grandfoobah can share the traefik config?

**Comment by arcanez** [comment]
> I haven't used traefik myself I'm afraid, but I would very much like if this issue was resolved in a proper way, so we/I can update https://convos.chat/doc/reverse-proxy with a proper example config.
> 
> By translating the nginx config, I would guess something like this should work:
> 
> ```
> version: "3"
> services:
>   convos:
>     image: nordaaker/convos:stable
>     container_name: convos
>     environment:
>       - CONVOS_REVERSE_PROXY=1
>     labels:
>       - "traefik.enable=true"
>       - "traefik.http.routers.whoami-secure.entrypoints=https"
>       - "traefik.http.middlewares.convos.headers.customrequestheaders.Host=convos.example.com"
>       - "traefik.http.middlewares.convos.headers.customrequestheaders.X-Request-Base=https://convos.example.com/"
> ```
> 
> What I don't understand is how traefik knows which SSL cert to use. Pretty sure a secure connection (meaning no self signed certs) is required for a proper Websocket connection.
> 
> Note to self: Update https://github.com/convos-chat/www.convos.chat/blob/master/doc/reverse-proxy.md with TLS/SSL examples.

this is my convos setup in my `docker-compose.yml`
```
  convos:
    image: nordaaker/convos
    restart: always
    volumes:
      - /var/convos/data:/data
    environment:
      - MOJO_REVERSE_PROXY=1
      - CONVOS_REVERSE_PROXY=1
      - VIRTUAL_HOST=convos.example.com
    container_name: convos
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.convos.rule=Host(`convos.example.com`)"
      - "traefik.http.services.convos.loadbalancer.server.port=3000"
      - "traefik.backend=convos"
      - "traefik.frontend.rule=Host:convos.example.com"
```
