### ISSUE TITLE
Reverse Proxy Caddy V2

### ISSUE THREAD

**Issue by matda59** [convos-chat/convos#725]
Reverse Proxy, HTTPS. Caddy V2

i found that when i attempt to log into my Convo docker instance running on Unraid i get met with a "Loading user data failed: The operation is insecure." found that you need to make additional changes to allow a reverse proxy. but the documentation and information on it is to complex to be frank. where do i make these changes? where do i put "CONVOS_REVERSE_PROXY=1 ./script/convos daemon --listen http://127.0.0.1:8080" for example in settings.json ? a new line? in the brackets? does anyone have a caddy V2 example?  where do i put these variables

**Comment by jhthorsen** [comment]
CONVOS_REVERSE_PROXY is an environment variable, so it must be set when you create your Docker service. Please consult the Docker help pages for how to do so.

I don't know anything about Caddy I'm afraid, but look at https://convos.chat/doc/reverse-proxy, since it contains generic information about what must be set. From your report it looks like Caddy is not set up to support WebSockets or maybe X-Request-Base is invalid. From the URL above:

> Convos and the web server need to be configured properly and [WebSockets](https://www.websocket.org/) need to be supported through the whole chain.

Also, web browsers may block WebSockets and other resources unless it is served over HTTPS. Maybe you have to set LetsEncrypt?

**Comment by JamesMowery** [comment]
Does someone have an example of how to get this working with Caddy v2? I have certs and everything with Cloudflare enabled. Websockets is said to "just work" with Caddy.

I can see the Convos website when I access it. I get the following error when I attempt to register a username/password:

`Failed fetching operationId "registerUser": SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON`

Here's my docker-compose.yml:
```
version: "3.8"

services:
  convos:
    image: ghcr.io/convos-chat/convos:alpha
    container_name: "convos"
    restart: unless-stopped
    ports:
      - "8085:3000"
    networks:
      - caddy
    volumes:
      - $HOME/containers/convos/data:/data
    environment:
      - CONVOS_REVERSE_PROXY=1

networks:
  caddy:
    external: true
```

And here is my Caddyfile:

```
#localhost on Docker = host.docker.internal
{
        https_port 443
        auto_https disable_certs
}

website.com {
        tls /data/certificate.pem /data/key.pem
}

*.website.com {
        tls /data/certificate.pem /data/key.pem

        @convos host convos.website.com
        handle @convos {
                reverse_proxy host.docker.internal:8085 {
                        header_up Host {host}
                        header_up X-Forwarded-For {remote}
                        header_up X-Request-Base "https://convos.website.com/"
                        
                         # I tried the following options but they don't work (not even sure if they are real options)
                        #header_up Upgrade {>Upgrade}
                        #header_up Connection {>Connection}
                        #request_body {
                        #       max_size 0
                        #}
                }
        }
```
