### ISSUE TITLE
Login Page "Sign In" button not using base path

### ISSUE THREAD

**Issue by shambleslol** [convos-chat/convos#806]
I noticed that the `/login` page's "Sign in" button is not respecting the X-Request-Base path. I used the example nginx config word-for-word and modified the upstream/domain to my instance. 

I can successfully browse to the `https://www.domain.com/convos/` which redirects to `https://www.domain.com/convos/login` but when clicking the "Sign in" button, it keeps trying to contact `https://www.domain.com/api/` and NOT `https://www.domain.com/convos/api`

All the other elements of the page load the correct path. 

Checked in both stable & alpha. 

Any suggestions? From what I can tell, it seems like the login may be hardcoded to use the /api

docker-compose.yml
```
version: "3"
services:
  convos:
    container_name: convos
    image: convos/convos:stable
    ports:
      - "8667:3000"
    volumes:
      - ./data/:/data
    environment:
      - CONVOS_REVERSE_PROXY=1
```

nginx conf
```
upstream convos_upstream { server 192.168.1.33:3000; }

server {
    server_name my.domain.com; 

    location /convos {
          proxy_pass http://convos_upstream;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          client_max_body_size 0;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          rewrite ^/convos/?(.*)$ /$1 break;
          proxy_set_header X-Request-Base "$scheme://$host/convos/";
    }
}
```
