### ISSUE TITLE
Caddy v2 Reverse Proxy Setup?

### ISSUE THREAD

**Issue by JamesMowery** [convos-chat/convos#882]
Does someone have an example of how to get this working with Caddy v2? I have certs and everything with Cloudflare enabled. Websockets are said to "just work" with Caddy v2, so no further setup should be necessary.

Here's my docker-compose.yml for convos:
```
version: "3.8"

services:
  convos:
    image: ghcr.io/convos-chat/convos:alpha
    container_name: "convos"
    restart: unless-stopped
    ports:
      - "8085:3000"
    networks:
      - caddy
    volumes:
      - $HOME/containers/convos/data:/data
    environment:
      - CONVOS_REVERSE_PROXY=1

networks:
  caddy:
    external: true
```

And here is my Caddyfile:

```
{
  https_port 443
  auto_https disable_certs
}

website.com {
  tls /data/certificate.pem /data/key.pem
}

# For wildcard domain handling
*.website.com {
  tls /data/certificate.pem /data/key.pem

  # Subdomain setup for "convos.website.com"
  @convos host convos.website.com
  handle @convos {
    reverse_proxy host.docker.internal:8085 {
      header_up Host {host}                  # not sure if "{host}" is valid; it's literally written as this
      header_up X-Forwarded-For {remote}     # not sure if {remote} is valid; it's literally written as this
      header_up X-Request-Base "https://convos.website.com/"

      # I tried the following options but they don't work (not even sure if they are real options)
      #header_up Upgrade {>Upgrade}
      #header_up Connection {>Connection}
      #request_body {
      #  max_size 0
      #}
    }
  }
}
```

EDIT: An example of what I tried first (so no one thinks I'm over-complicating it intentionally):
```
{
  https_port 443
    auto_https disable_certs
}

website.com {
  tls /data/certificate.pem /data/key.pem
}

# For wildcard domain handling
*.website.com {
  tls /data/certificate.pem /data/key.pem

  # Subdomain setup for "convos.website.com"
  @convos host convos.website.com
  handle @convos {
    reverse_proxy host.docker.internal:8085
  }
}
```

I can see the Convos website when I access it. I get the following error when I attempt to register a username/password:

`Failed fetching operationId "registerUser": SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON`

I asked ChatGPT to generate the above config while trying to convert it from the nginx and apache one (I wasn't expecting it to work, but it at least gets me to the homepage). I don't really know if any of the config sections containing "header_up" is valid or not, but I do have several other services running with a very similar setup (without any "header_up" items) working perfectly.
