### ISSUE TITLE
convos exited with code 0

### ISSUE THREAD

**Issue by trymbill** [convos-chat/convos#885]
**Describe the bug**
I'm trying to run Convos with Docker and been struggling getting past the first user being registered. I've tried a bunch of things (permissions, UID/GID, different reverse proxy settings, different browsers, etc) but can't find the source of the issue. Every time I try and 'Sign up' the initial user, I get this:

<img width="849" alt="Screenshot 2024-03-07 at 22 32 46" src="https://github.com/convos-chat/convos/assets/658727/da5bc7b8-f140-444e-81bd-ea2f0e0c48d5">

Here's the docker-compose.yaml config:
```yaml
convos:
  container_name: "convos"
  image: "ghcr.io/convos-chat/convos:stable"
  user: "1000:100"
  environment:
    - "CONVOS_LOG_LEVEL=trace"
    - "CONVOS_REVERSE_PROXY=1"
    - "CONVOS_REQUEST_BASE=https://my.domain.com/"
  volumes:
    - "/path/to/convos/data:/data"
  restart: "unless-stopped"
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.convos.tls.certresolver=letsencrypt"
    - "traefik.http.routers.convos.entrypoints=https"
    - "traefik.http.routers.convos.rule=Host(`my.domain.com`)"
    - "traefik.http.services.convos.loadbalancer.server.port=3000"
    - "traefik.backend=convos"
    - "traefik.frontend.rule=Host:my.domain.com"
```

Here's the call to `/api/user/register.json` being made in Postman and a terminal open on the docker container running Convos. As you can see the container exits with `code 0` and nothing in the logs, even on `CONVOS_LOG_LEVEL=trace`, to explain why:

https://github.com/convos-chat/convos/assets/658727/ff9c5964-88da-4bf7-ac5d-ad65328780ab

Any ideas what could be going on here?

**Environment:**
 - OS: Ubuntu
 - Browser: Chrome, Firefox, Arc
 - Version: ghcr.io/convos-chat/convos:stable
